"""empty message

Revision ID: 43ea60094993
Revises: 595ecf0ea2be
Create Date: 2022-09-29 10:39:31.125512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ea60094993'
down_revision = '595ecf0ea2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cool', sa.Integer(), nullable=True),
    sa.Column('shit', sa.Integer(), nullable=True),
    sa.Column('angry', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'invalid_tokens', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'post_id')
    op.drop_constraint(None, 'invalid_tokens', type_='foreignkey')
    op.drop_table('post')
    # ### end Alembic commands ###
