"""empty message

Revision ID: 595ecf0ea2be
Revises: a2f0c41bf38a
Create Date: 2022-09-28 21:32:20.985692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595ecf0ea2be'
down_revision = 'a2f0c41bf38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'invalid_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invalid_tokens', type_='foreignkey')
    # ### end Alembic commands ###
