"""empty message

Revision ID: d6c3cd34fe43
Revises: 43ea60094993
Create Date: 2022-09-29 11:25:24.417928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c3cd34fe43'
down_revision = '43ea60094993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_post_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_post_id_fkey', 'users', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
